var SC_APPEARANCE2 = {
	'weekdays':  ['S&oslash;', 'Ma', 'Ti', 'On', 'To', 'Fr', 'L&oslash'], 
	'longmonth' : ['Januar','Februar','Marts','April','Maj','Juni','Juli','August','September','Oktober','November','December'],
	'messages' : {
				'Warning' : 'Warning: the date entered does not meet preset date format',
				'AltPrevYear' : 'to previos year',
				'AltNextYear' : 'to next year',
				'AltPrevMonth' : 'to previos month',
				'AltNextMonth' : 'to next month'
	},
	'CalDiv' : 'clsCalDiv2',
	'OuterFrame' : 'clsOuterFrame2',
	'InnerFrame' : 'clsInnerFrame2',
	'TopPartNavpanel' : 'clsTopPartNavpanel2',
	'BottomPartNavpanel' : 'clsBottomPartNavpanel2',
	'MidRow' : 'clsMidRow2',
	'DateGrid':'clsDateGrid2',
	'WeekDay':'clsWeekDay2',
	'WorkDayCell': 'clsWorkDayCell2',
	'HoliDayCell': 'clsHoliDayCell2',
	'OtherMonthDayCell': 'clsOtherMonthDayCell2',
	'SelectedDayCell': 'clsSelectedDayCell2',
	'CurrentMonthDay': 'clsCurrentMonthDay2',
	'OtherMonthDay': 'clsOtherMonthDay2',
	'SelectedDay': 'clsSelectedDay2',
	'InfoTitle':'clsInfoTitle2',
	'DataArea':'clsDataArea2',
	'PrevYear':'img/prev_year2.gif',
	'PrevMonth':'img/prev_month2.gif',
	'NextYear':'img/next_year2.gif',
	'NextMonth':'img/next_month2.gif',
	'IcoCalUnVis': 'img/dpr_unvis2.gif',
	'IcoCalVis': 'img/dpr_vis2.gif'
};